In [2]:
import statistics
data = vac_nums = [0,0,0,0,0,
            1,1,1,1,1,1,1,1,
            2,2,2,2,
            3,3,3
            ]
    
#your code goes here
res= statistics.mean(data)

print(res)

1.25


In [7]:
data = [14, 18, 19, 24, 26, 33, 42, 55, 67] 
x = statistics.pvariance(data, mu=None)
print(x)

292.5432098765432


In [8]:
from math import *
print(sqrt(x))

17.10389458212787


In [10]:
import numpy as np 
x = np.array([1, 2, 3, 4]) 
print(x[0])

1


In [11]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
print(x[1][2])

6


In [12]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(x.ndim) # 2
print(x.size) # 9
print(x.shape) # (3, 3)

2
9
(3, 3)


In [14]:
x = np.array([1, 2, 3,4,5])
y = np.append(x,4)
z = np.delete(x,0)
j = np.sort(x)
print(x)
print(y)
print(z)
print(j)

[1 2 3 4 5]
[1 2 3 4 5 4]
[2 3 4 5]
[1 2 3 4 5]


In [15]:
x = np.arange(2,10,3)
print(x)

[2 5 8]


In [17]:
x = np.arange(2, 8, 2)
print(x)
x = np.append(x, x.size)
print(x)
x = np.sort(x)
print(x)
print(x[1])

[2 4 6]
[2 4 6 3]
[2 3 4 6]
3


In [21]:
x = np.arange(1,7)
print(x)

[1 2 3 4 5 6]


In [22]:
z = x.reshape(3,2)
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
x = np.array([[1, 2], [4, 5], [7, 8]])

In [24]:
print(x)

[[1 2]
 [4 5]
 [7 8]]


In [25]:
z = x.reshape(6)
print(z)

[1 2 4 5 7 8]


In [26]:
x = np.arange(1, 8, 3)
z = x.reshape(3, 1)
print(z[1][0])


4


In [27]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [28]:
print(x[0:2])
print(x[5:])
print(x[:2])
print(x[-3:])

[1 2]
[6 7 8 9]
[1 2]
[7 8 9]


In [29]:
print(x[x<4])

[1 2 3]


In [31]:
print(x[(x>5) & ( x%2==0)])

[6 8]


In [32]:
x = np.arange(1,10)
print(x.sum())

45


In [33]:
y = x*2
print(y)

[ 2  4  6  8 10 12 14 16 18]


In [34]:
x = np.array([14,18,19,24,26,33,42,55,67])
print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

33.111111111111114
26.0
292.5432098765432
17.10389458212787


In [35]:
x = np.arange(3, 9)
z = x.reshape(2, 3)
print(z[1][1])

7


In [36]:
x = np.arange(1, 5)
x = x*2
print(x[:3].sum())

12


In [37]:
import numpy as np

data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])
print(np.mean(data))

260312.5


In [39]:
print(np.std(data))

130053.69984644804


In [40]:
import pandas as pd 
data = {
   'ages': [14, 18, 24, 42],
   'heights': [165, 180, 176, 184]
} 
df = pd.DataFrame(data)
print(df)

   ages  heights
0    14      165
1    18      180
2    24      176
3    42      184


In [41]:
x = {
'a': [1, 2],
'b': [3, 4],
'c': [5, 6]
}
df = pd.DataFrame(x)

In [42]:
print(df)

   a  b  c
0  1  3  5
1  2  4  6
